name = "prism-registry"
main = "src/index.ts"
compatibility_date = "2026-04-01"

# These are set via `wrangler secret put` -- NOT here
# GH_TOKEN = "your github pat"
# REGISTRY_TOKENS = "token1,token2,token3"

[vars]
GH_OWNER = "ProsusAI"
GH_REPO = "prism-registry-demo"
GH_BRANCH = "main"
